@Restaurants.API_HostAddress = https://localhost:7005
@token = CfDJ8H5qBllRvKlBisTDrOCmeBocbpokJki9pZHXx71qNobpNZYjyb-rZ5KPkjfukAKHpQcDsF1txQ6MGNJQ5lGZyPdexOrcWfG4f8V1yZIej2J3HOhsGUGE5Ag7AjI3_uR4Y9NbfoLmWgamMI7IZR_lZNO5GBsiGCjW668tV_CqbPA_slOURNQMNNcMuBUyNX6L_WYlfxW6H9YxQaNjDvuAYOR2kRwZl1UwmVsOzlRAxhUnQ3mwyLXxfZKieF9gb-ccFu95g1LIZqp_O3fCv4rYnMhMKbtAccUQqeDzhaXu97-5SLc8igMpNLMTUP2G0DLPO3y3jZs4l58Ox-WEIu8HL0dFacRoECFpFDOyLEm2FZfqdBGP0_zj9Ci4vUz1wCY2eKU7jrA3fwyJDgdn2j6Bv305UwcswSH2I0CGh7hL6Sg28qRsKGWTPJ5_wWg86HbD8XbNr9UyryoI7Q4WpqHXfjGZ9rw1HAIMDNPmbKPeXF0dx0LXWzVV967ys0-euPkNCbSnVMBFpUbiRhRXQsOwtq6vEudmYjWUEQTG3n7qKVA3o5jwgWZBX7t35lQUQXr3BzqpBmHFEW833Gvc1FrzU5dWXWPegJjokXeZ3gWOXOjTXbxc2RqqCl0mURt8nzb4WrqH5DsJGTkQqmUdgrgcLdWbGLf65l8nqVlY7W0Mdeql5-L1whYzR6Hi7-IYvaPBW6PjzpuIii_3uBUoX_iH-F3Fjw8cE2n2NcMiZ_-oc6kF8n99maHdfYfbN_UGZyiMcGGpz2iyBY0_SM78EzhJlen9YUhzLXlbfFIqJcCtBz1JXvU_pVAmOB35Ahw7joZxIGtGuD-Yl_R1Vvg0X5z0CBFpq0qtmzR3BHvTYnwsI3gw-MZ7x_znBdK_SEQLrxq0qg

GET {{Restaurants.API_HostAddress}}/api/restaurants?SearchPhrase&pageSize=10&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Owner2 Restaurant2",
  "Description": "This is a sample restaurant description.",
  "Category": "Sample Category",
  "HasDelivery": true,
  "ContactEmail": "sample@example.com",
  "ContactNumber": "123-456-7890",
  "City": "Sample City",
  "Street": "Sample Street",
  "PostalCode": "12345"
}

###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/121488

###



PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2004
Authorization: Bearer {{token}}
Content-Type: application/json

{
    
    "Name": "Sample Restaurant 2",
    "Description": "This is a sample restaurant description.",
    "HasDelivery": false,
    "Category": "Fast Food"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat souce",
  "Price": 25,
  "KiloCalories": 750
}

###

Delete {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner2@gmail.com",
  "password": "Password1!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@gmail.com",
  "password": "Password1!"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "UserEmail": "owner2@gmail.com",
  "RoleName"": "Owner"
}

###
