@Restaurants.API_HostAddress = https://localhost:7005
@token = CfDJ8H5qBllRvKlBisTDrOCmeBpgty9Vgs2M9G62xqzOVTzCVIrqOT1SPLvaNWxOfMDoMS9cVpjpMpUQqce7GReEshiMBRoTjJ4eKJwmDraAJBAzrStSrzJ606yOtPtdFrboeNAdFDPRw5gNluHwjKMivqJnoUXraSJFkWkB2bmTBqWqYNfYhgZ4QrHQZ7ikcCM2r6Ws3QPDncYoDO7ndKU0djSkBNRlWsFRxC64WynHQO0CgHXojXyz1AXR8tO5IvWWWzEWPo29akVYbZVafBBVupBdx0nDv9QFeq0w3H9tact4Pw9vL3FPWxDiB_j2km2u1zy75AspSfYAvpub4mU9cZYOnzfNjPuLcUE-jJMswd7GpJluMussKwoiJdetswz8CcbJnEwO4Ub0WPwTC_oDXsCrjEjwczao-6raqIss2bXvjsbApI0Xvz8tYO7_Z3LUZSYN134d561XpEHQtNOgxZoqnwAyisZ1mNiDXePe8sNs_zA2AJrA_m0_5AbJtUtMdz76-aK8LxePQRidRhuYmmWzHwQ6rmE_bChPispG3W8utfcYmL58dIuzdYAsj1v4_MVdr1QlW3II8y-WLJBVhKKJQ2-uCQgun622Rpkv_u_Z_1x04fvwhPdHQ1iJJXhbG4USc5By6zcFL5206oTEst7gcd69in7_g7QVTZsE4vznu-k3fTXaaafSp1Hov5XzIpWzof5g5EcSGGQI6LYnCOCRQMXKMNR6oUbw0P1ZfQPiGw4kU35fXwmIc7ZeDpeoKP2iEFgwdq8L5zKsHJ267KYrEe9BC1ADt8CCr6buiF81

GET {{Restaurants.API_HostAddress}}/api/restaurants?SearchPhrase&pageSize=10&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization: Bearer {{token}}

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Owner2 Restaurant2",
  "Description": "This is a sample restaurant description.",
  "Category": "Sample Category",
  "HasDelivery": true,
  "ContactEmail": "sample@example.com",
  "ContactNumber": "123-456-7890",
  "City": "Sample City",
  "Street": "Sample Street",
  "PostalCode": "12345"
}

###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/121488

###



PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2004
Authorization: Bearer {{token}}
Content-Type: application/json

{
    
    "Name": "Sample Restaurant 2",
    "Description": "This is a sample restaurant description.",
    "HasDelivery": false,
    "Category": "Fast Food"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat souce",
  "Price": 25,
  "KiloCalories": 750
}

###

Delete {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner2@gmail.com",
  "password": "Password1!"
}
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner2@gmail.com",
  "password": "Password1!"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "UserEmail": "owner2@gmail.com",
  "RoleName"": "Owner"
}

###
